# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- dev
resources:
  containers:
  - container: mysql
    image: mysql:8.0.18
    environment:
    - MYSQL_DATABASES=api
    - MYSQL_ROOT_PASSWORD=root
    
pool:
  vmImage: 'ubuntu-latest'

services:
  mysql: mysql
  
steps:
- bash: |
    mysql -uroot -proot -e "create database api; select version();"
  displayName: init database
  
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
